### ISSUE TITLE
equals/not search conditions throw an error

### ISSUE THREAD

**Issue by cfisher5** [DataTables/SearchBuilder#15]
as of a couple months ago, we have been experiencing an issue with searchbuilder's "equals" and "not" filters. when we attempt to try those filters, the dropdown is empty and unclickable, and the javascript console shows: 
```
dataTables.searchBuilder.min.js:4 Uncaught TypeError: r is not a function
    at w.initSelect [as init] (dataTables.searchBuilder.min.js:4:20822)
    at w._clearValue (dataTables.searchBuilder.min.js:4:13664)
    at HTMLSelectElement.<anonymous> (dataTables.searchBuilder.min.js:4:11962)
    at HTMLSelectElement.dispatch (jquery-3.7.0.js:5135:27)
    at elemData.handle (jquery-3.7.0.js:4939:28)
```

we are bringing in the following scripts...maybe some of them don't play nice together? 
```
<script type="text/javascript" src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/searchbuilder/1.7.0/js/dataTables.searchBuilder.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/datetime/1.4.0/js/dataTables.dateTime.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/plug-ins/1.13.4/sorting/absolute.js"></script>
```

We are experiencing this issue on simple text columns and int columns

**Comment by AllanJard** [comment]
It appears [to work in this example](https://datatables.net/extensions/searchbuilder/examples/initialisation/simple.html). Can you link to a test case showing the issue please?

I should also note that the versions indicate that you are using old versions of the various bits of software. The latest can be obtained from [the download builder](https://datatables.net/download/index).

**Comment by cfisher5** [comment]
you're right, my fault. fixed by updating script versions
