### ISSUE TITLE
Typo for dtsp-joiner class ?

### ISSUE THREAD

**Issue by robin-siegl** [DataTables/SearchBuilder#18]
Hello,
i don't know if this is intentional or a typo, but every class starts with `dtsb` except for `dtsp-joiner`.
Was this intentional or is this a typo?

Search: [Code search results (github.com)](https://github.com/search?q=org%3ADataTables%20dtsp-joiner&type=code)

**Comment by AllanJard** [comment]
Yup - looks like a typo (was probably thinking of SearchPanes). Thanks for flagging that up.

**Comment by AllanJard** [comment]
Fixed here: https://github.com/DataTables/SearchBuilder/commit/0afaf2d6f2e76c0fa8c47a0acaeb8dbca85d411c . Will be in the next release.

Thanks again!
