### ISSUE TITLE
DataTables.luxon() is not a function.

### ISSUE THREAD

**Issue by ska737** [DataTables/SearchBuilder#20]
While trying to integrate luxon into the Search Builder, I get the error `Uncaught TypeError: DataTable.luxon is not a function`.

Looking at your documentation, and the [example](https://datatables.net/extensions/searchbuilder/examples/initialisation/date-fmt-luxon.html) of the integration of luxon with the Search Builder, the console on that page gives the same error.

**Comment by AllanJard** [comment]
Sorry about that. The function to call is `DataTable.datetime()` - I've [committed the fix](https://github.com/DataTables/SearchBuilder/commit/34bf2800278195a72959b4269688af5bb5e12f08) and twill update the website soon.
