### ISSUE TITLE
Custom condition naming conflicts

### ISSUE THREAD

**Issue by MichaelRuggiero250** [DataTables/SearchBuilder#22]
When creating a new custom condition there is an issue if you name the condition so that it contains the value "num" such as "enumValues", the Criteria.getDetails function will check if the condition name includes the value "num", and if so apply a regex expression to clear out any non digit characters. 

This yielded some painful debugging on why my search values where coming back as an empty string "" after triggering a doSearch, but after renaming the condition it fixed the issue. The getDetails function should explicitly check the full name of the condition rather then using includes to prevent possible conflicts with default condition names and custom condition names.

The mentioned line is [here](https://github.com/DataTables/SearchBuilder/blob/master/src/criteria.ts#L2076)

**Comment by AllanJard** [comment]
That's a really good point and my apologies that you have problems with this. I think this section of SearchBuilder could really do with a bit of a revamp. I've [committed](https://github.com/DataTables/SearchBuilder/commit/739084eda26466fe931c08410fdcd4d841d2bc2c) a change to limit the match to DataTables' built in data types for the moment though.

**Comment by AllanJard** [comment]
That's a really good point and my apologies that you have problems with this. I think this section of SearchBuilder could really do with a bit of a revamp. I've [committed](https://github.com/DataTables/SearchBuilder/commit/739084eda26466fe931c08410fdcd4d841d2bc2c) a change to limit the match to DataTables' built in data types for the moment though.
