### ISSUE TITLE
Basic Example - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by burakt91** [DataTables/SearchBuilder#4]
When using official basic example on here https://datatables.net/extensions/searchbuilder/examples/initialisation/simple.html it throws RangeError: Maximum call stack size exceeded in the console and search builder become broken. 

Steps to reproduce:
1. Click Add Condition. Age Between 30 and 40.
2. Click Add Condition again. 
3. JS error happens in the console.

![1](https://user-images.githubusercontent.com/18482904/148743651-267173dc-9f15-4d48-852a-ba1f2f5003aa.png)
![2](https://user-images.githubusercontent.com/18482904/148743654-cbe0202c-4e2d-41b8-be09-f4614a1c3e07.png)

**Comment by AllanJard** [comment]
Hi - thanks for the bug report. This has actually been fixed already as you can see when using the nightly version: http://live.datatables.net/ciquxeto/1/edit .

I'll get a new release tagged and packaged up this week.
