### ISSUE TITLE
Between filter not working with newer moment.js versions

### ISSUE THREAD

**Issue by jjacobson** [DataTables/SearchBuilder#5]
It looks like some changes to the way moment.js parses dates have caused issues with the between filter when using date formatting. 

Example here: http://live.datatables.net/macizuwa/11/watch

When selecting the first date field while using either the "between" or "not between" filters, you get an exception due to the way moment now parsing dates without a value. I have only tested this when server side processing is enabled.

When the empty date is converted to a moment object:

```javascript
              else if (this.s.type.includes('moment')) {
                    for (var i = 0; i < this.s.value.length; i++) {
                        this.s.value[i] = moment(this.s.value[i], this.s.dateFormat).toISOString(); //here
                    }
                }
```

It does not take into account whether the date has a value. When toISOString() is called it results in the second (unfilled) date being set to null. Then when toString() is later called it results in an exception:

```javascript                
            return {
                condition: this.s.condition,
                data: this.s.data,
                origData: this.s.origData,
                type: this.s.type,
                value: this.s.value.map(function (a) { return a.toString(); }) // here
            };

```

```javascript
dataTables.searchBuilder.js:294 Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at dataTables.searchBuilder.js:294:65
    at Array.map (<anonymous>)
    at Criteria.getDetails (dataTables.searchBuilder.js:294:37)
    at Group.getDetails (dataTables.searchBuilder.js:2506:53)
    at SearchBuilder.getDetails (dataTables.searchBuilder.js:3206:36)
    at HTMLTableElement.<anonymous> (dataTables.searchBuilder.js:3323:69)
    at HTMLTableElement.dispatch (jquery.min.js:2:43064)
    at HTMLTableElement.v.handle (jquery.min.js:2:41048)
    at Object.trigger (jquery.min.js:2:71515)
    at HTMLTableElement.<anonymous> (jquery.min.js:2:72110)
```

Thanks.

**Comment by SandyDatatables** [comment]
Hi @jjacobson ,

Thanks for pointing that out. The above commit should catch the error.

Thanks,
Sandy
