### ISSUE TITLE
Filterung numbers does not allow negative values

### ISSUE THREAD

**Issue by maximilian0311** [DataTables/SearchBuilder#7]
Hi guys,
I'm using searchBuilder to filter a table with meausrements server-side. In one of my table columns is the environment-temperature in °C, which can be negative. I found out that filtering for the negative number still causes a ajax-request with the absolute value which causes the returned result to be wrong.

I found out, that in your regex for numbers you should switch from this 
**/[^0-9.]/g**
to this 
**/(?!^-)[^0-9.]/g**
to include negative numbers.

Regards
Max

**Comment by AllanJard** [comment]
Hi Max,

Many thanks - totally agree! It looks like we should perhaps have a bit more DRY code in the criteria searching for numbers - there is a lot of repetition there, e.g.:

```
				let val = value.indexOf('-') === 0 ?
					'-' + value.replace(/[^0-9.]/g, '') :
					value.replace(/[^0-9.]/g, '');
```

Which could be done with a single regex and the regex pulled out so it is only created once.

I'll ask Sandy to look at this when he is back next Thursday.

**Comment by SandyDatatables** [comment]
Hi @maximilian0311 ,

Thanks again for highlighting this to us.

I've made the above commit to tidy up the way we deformat the numbers and am using the regex provided by yourself.

Thanks,
Sandy
