### ISSUE TITLE
Bug: searchBuilder.columns do not work for "Bfrtip" dom

### ISSUE THREAD

**Issue by ppizarror** [DataTables/SearchBuilder#9]
Hello. I've noticed a bug regarding the "columns" option. In our case, if using "Bfrtip" instead of "Qlfrtip", the columns provided in the ``searchBuilder`` object are ignored.

Example:
```js
options = {
  ...
  dom: 'Qlfrtip',
  header: [
      app.lang.id, // 0
      app.lang.user, // 1
      app.lang.project, // 2
      app.lang.process, // 3
      app.lang.module_monitor_timeline_database_title, // 4
      app.lang.type, // 5
      'Ti', // 6
      'Tf', // 7
      app.lang.manual, // 8
  ],
  searchBuilder: {
      columns: [1, 2, 3, 4, 5, 6, 7, 8],
  },
};
```
![image](https://user-images.githubusercontent.com/12925256/221240454-5089efad-25a2-4758-88ca-7f76adf1b2c2.png)

Now, using "Bfrtip" option, the first column (0) which is the ID is being displayed:
```js
options = {
  ...
  dom: 'Bfrtip',
  ...
  searchBuilder: {
      columns: [1, 2, 3, 4, 5, 6, 7, 8],
  },
};
```
![image](https://user-images.githubusercontent.com/12925256/221240843-f671f345-3654-49af-9016-dba8db838dfe.png)

Grettings 😄, and thanks for the fantastic DataTables!!

**Comment by ppizarror** [comment]
Using datatables ``v1.13.2`` and searchbuilder ``v1.4.0``. Each other extension is also in its latest version.

**Comment by AllanJard** [comment]
Can you link to a test case showing the issue please?

**Comment by ppizarror** [comment]
> Can you link to a test case showing the issue please?

Sure, see https://jsfiddle.net/ppizarror/p7w9vLk4/26/. The first table has "ID" column hidden. The second table, however, still shows the hidden column.

**Comment by AllanJard** [comment]
I'm with you now - thanks! When you use the SearchBuilder button, you need to provide the options directly to the button. They are not read from the `searchBuilder` object at the top level of the DataTable configuration object.

There is an example of how to do it here: https://datatables.net/extensions/searchbuilder/examples/initialisation/buttonOptions.html .
